[package]
name = "street-smack"
version = "0.1.0"
description = "Street Smack — Real-time meme aura battle on Solana with MagicBlock Ephemeral Rollups"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "street_smack"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []

[dependencies]
anchor-lang = "1.0.2"
ephemeral-rollups-sdk = { version = "=0.16.2", features = ["anchor", "access-control", "vrf"] }
solana-instructions-sysvar = "3.0.1"
solana-pubkey = "3.0.0"
solana-sha256-hasher = "3.1.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
